services:
  - type: web
    name: sogrim-app-v2
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://sogrim-api.onrender.com
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
